language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - python setup.py install
  - pip install flake8

script:
  - python setup.py test
  - flake8 setup.py inception tests

after_success:
  - pip install python-coveralls
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change
